Repository pooranjoyb/BeatBridge, pull requests merged in 2023-10, with the labels that each got.

#8 fix : errors in CONTRIBUTING.md
  CONTRIBUTING.md
  package-lock.json
  src/App.jsx
  src/Components/Player.jsx
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#22 Feat: CI/CD workflow to check code formatting and linting.
  .eslintrc.cjs
  .github/workflows/.prettierrc
  .github/workflows/lint.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  backend/README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/Components/FeaturesHomePage.jsx
  src/Components/Home.jsx
  src/main.jsx
  src/tailwindcss/output.css
  tailwind.config.js
  vite.config.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#31 Integrated Spotify API and added search functionality
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Player.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#32 Added table of contents
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#37 Dependabot improvements integrated
  .github/Dependabot.yml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
